### ISSUE TITLE
Unable to run demo: dependencies do not exist

### ISSUE THREAD

**Issue by re3lex** [jfree/jfree-fxdemos#2]
Hi,

I have cloned repo and executed `mvn javafx:run` in master branch but got the error:

```
[ERROR] Failed to execute goal on project org.jfree.fx.demos: Could not resolve dependencies for project org.jfree:org.jfree.fx.demos:jar:2.0: The following artifacts could not be resolved: org.jfree:jfreechart:jar:1.6.0-SNAPSHOT, org.jfree:jfreechart-fx:jar:2.0-SNAPSHOT: Could not find artifact org.jfree:jfreechart:jar:1.6.0-SNAPSHOT -> [Help 1]
```

I have checked in maven central repo: last published version for 
 * jfreechart is 1.5
 * jfreechart-fx is 1.0.1

So how to resolve dependencies?
Should I add some specific maven repository?

**Comment by jfree** [comment]
Sorry for this.  Can you try with the changes I just committed?  It works for me now.
